version: '1.0'
services:
  backend:
    restart: always
    build:
      context: ./backend
    ports:
      - "8000:8000"

  frontend:
    restart: always
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
